theme: jekyll-theme-cayman

SER ADULTO

SALUD
Alimentación
Higiene personal
Orden y limpieza entorno
Imagen y vestimenta
Deporte y actividad física
Consumo drogas y adicciones mentales
Dormir
Resfriado o necesidad medicación u atención médica

RESPONSABILIDADES
Planificación económica, deudas, ahorros
Estudios
Trabajo
Getting ur shit together and being there, with good attitude, going forward always. Por lo menos estate alli
Compromisos
Responsabilidades personales

RELACIONES
Familia
Pareja
Amigos
Figuras autoridad
Imagen general conocidos
Imagen primera impresion desconocidos

OCIO
Solitario
Social

CRECIMIENTO Y A PRENCIZAJE

PROYECTOS
Con rentabilidad economica
Con buen fin/ regalo
Con fin de aprender
Con fin de divertirse

ACTITUD, HÁBITOS Y DISCIPLINA
Gestión del tiempo
Gestión del dinero
  Ingresos activos
  Ingresos pasivos
  Gastos activos
  Gastos Pasivos
  Inversión en bolsa/ crypto/ skins/...

ORIENTACIÓN DE VIDA, PLANES DE FUTURO, Y MOTIVO POR EL QUE SEGUIR

ESTADO EMOCIONAL
